### ISSUE TITLE
docker部署无法启动，报错502

### ISSUE THREAD

**Issue by ynbl07** [imsyy/SPlayer#318]
### 是网页端还是客户端

网页

### 当前系统环境

Ubuntu

### 当前 Node.js 及 npm 版本

无

### 当前版本

3

### 具体信息

使用docker部署后，无法启动，日志如下：
2024/12/24 16:42:26 [notice] 7#7: using the "epoll" event method
2024/12/24 16:42:26 [notice] 7#7: nginx/1.27.2
2024/12/24 16:42:26 [notice] 7#7: built by gcc 13.2.1 20240309 (Alpine 13.2.1_git20240309) 
2024/12/24 16:42:26 [notice] 7#7: OS: Linux 6.6.67-ophub
2024/12/24 16:42:26 [notice] 7#7: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/12/24 16:42:26 [notice] 8#8: start worker processes
2024/12/24 16:42:26 [notice] 8#8: start worker process 9
2024/12/24 16:42:26 [notice] 8#8: start worker process 10
2024/12/24 16:42:26 [notice] 8#8: start worker process 11
2024/12/24 16:42:26 [notice] 8#8: start worker process 12
{
  status: 502,
  body: {
    code: 502,
    msg: AxiosError [AggregateError]
        at AxiosError.from (/usr/local/lib/node_modules/NeteaseCloudMusicApi/node_modules/axios/dist/node/axios.cjs:876:14)
        at RedirectableRequest.handleRequestError (/usr/local/lib/node_modules/NeteaseCloudMusicApi/node_modules/axios/dist/node/axios.cjs:3156:25)
        at RedirectableRequest.emit (node:events:519:28)
        at eventHandlers.<computed> (/usr/local/lib/node_modules/NeteaseCloudMusicApi/node_modules/follow-redirects/index.js:49:24)
        at ClientRequest.emit (node:events:519:28)
        at TLSSocket.socketErrorListener (node:_http_client:500:9)
        at TLSSocket.emit (node:events:519:28)
        at emitErrorNT (node:internal/streams/destroy:169:8)
        at emitErrorCloseNT (node:internal/streams/destroy:128:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
        at Axios.request (/usr/local/lib/node_modules/NeteaseCloudMusicApi/node_modules/axios/dist/node/axios.cjs:4287:41)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      code: 'ETIMEDOUT',
      errors: [Array],
      config: [Object],
      request: [Writable],
      cause: [AggregateError]
    }
  },
  cookie: []
}
{
  status: 502,
  body: {
    code: 502,
    msg: AxiosError [AggregateError]
        at AxiosError.from (/usr/local/lib/node_modules/NeteaseCloudMusicApi/node_modules/axios/dist/node/axios.cjs:876:14)
        at RedirectableRequest.handleRequestError (/usr/local/lib/node_modules/NeteaseCloudMusicApi/node_modules/axios/dist/node/axios.cjs:3156:25)
        at RedirectableRequest.emit (node:events:519:28)
        at eventHandlers.<computed> (/usr/local/lib/node_modules/NeteaseCloudMusicApi/node_modules/follow-redirects/index.js:49:24)
        at ClientRequest.emit (node:events:519:28)
        at TLSSocket.socketErrorListener (node:_http_client:500:9)
        at TLSSocket.emit (node:events:519:28)
        at emitErrorNT (node:internal/streams/destroy:169:8)
        at emitErrorCloseNT (node:internal/streams/destroy:128:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
        at Axios.request (/usr/local/lib/node_modules/NeteaseCloudMusicApi/node_modules/axios/dist/node/axios.cjs:4287:41)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      code: 'ETIMEDOUT',
      errors: [Array],
      config: [Object],
      request: [Writable],
      cause: [AggregateError]
    }
  },
  cookie: []
}
server running @ http://localhost:3000

**Comment by sexyfeifan** [comment]
2025/01/02 18:18:15 [notice] 1#1: using the "epoll" event method

2025/01/02 18:18:15 [notice] 1#1: nginx/1.27.3

2025/01/02 18:18:15 [notice] 1#1: built by gcc 13.2.1 20240309 (Alpine 13.2.1_git20240309) 

2025/01/02 18:18:15 [notice] 1#1: OS: Linux 6.6.38-trim

2025/01/02 18:18:15 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576

2025/01/02 18:18:15 [notice] 7#7: start worker processes

2025/01/02 18:18:15 [notice] 7#7: start worker process 8

2025/01/02 18:18:15 [notice] 7#7: start worker process 9

2025/01/02 18:18:15 [notice] 7#7: start worker process 10

2025/01/02 18:18:15 [notice] 7#7: start worker process 11

2025/01/02 18:18:20 [notice] 1#1: using the "epoll" event method

2025/01/02 18:18:20 [notice] 1#1: nginx/1.27.3

2025/01/02 18:18:20 [notice] 1#1: built by gcc 13.2.1 20240309 (Alpine 13.2.1_git20240309) 

2025/01/02 18:18:20 [notice] 1#1: OS: Linux 6.6.38-trim

2025/01/02 18:18:20 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576

2025/01/02 18:18:20 [notice] 7#7: start worker processes

2025/01/02 18:18:20 [notice] 7#7: start worker process 8

2025/01/02 18:18:20 [notice] 7#7: start worker process 9

2025/01/02 18:18:20 [notice] 7#7: start worker process 10

2025/01/02 18:18:20 [notice] 7#7: start worker process 11

2025/01/02 18:18:20 [notice] 7#7: start worker process 12

2025/01/02 18:18:20 [notice] 7#7: start worker process 13
