### ISSUE TITLE
构建客户端问题

### ISSUE THREAD

**Issue by NokoLov1** [imsyy/SPlayer#90]
### 是网页端还是客户端

客户端

### 当前系统环境

win10

### 当前版本

v2.0.0-beta.2

### 具体信息

构建客户端时返回：
/www/wwwroot/SPlayerMusic/node_modules/minizlib/index.js:192
[_superWrite] (data) {
^
TypeError: Class extends value #<Object> is not a constructor or null
at Object.<anonymous> (/www/wwwroot/SPlayerMusic/node_modules/minizlib/index.js:192:4)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
at Module.load (node:internal/modules/cjs/loader:1207:32)
at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
at Module.require (node:internal/modules/cjs/loader:1235:19)
at require (node:internal/modules/helpers:176:18)
at Object.<anonymous> (/www/wwwroot/SPlayerMusic/node_modules/tar/lib/pack.js:26:14)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
at Module.load (node:internal/modules/cjs/loader:1207:32)
at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
at Module.require (node:internal/modules/cjs/loader:1235:19)
at require (node:internal/modules/helpers:176:18)
at Object.<anonymous> (/www/wwwroot/SPlayerMusic/node_modules/tar/lib/create.js:6:14)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
ELIFECYCLE  Command failed with exit code 1.

**Comment by imsyy** [comment]
删除 `node_modules` 目录重新安装下依赖试试
