### ISSUE TITLE
ArchLinux下无法运行

### ISSUE THREAD

**Issue by zxp19821005** [imsyy/SPlayer#93]
### 是网页端还是客户端

客户端

### 当前系统环境

EndeavourOS 6.1.63-1-lts

### 当前 Node.js 及 npm 版本

v18.18.2/v10.2.4

### 当前版本

v2.0.0-beta.2

### 具体信息

我计划将该软件包移植到ArchLinux的AUR，但是下载了deb包 后解压直接运行，报错：
```
$ ./splayer 
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
[133345:1130/103630.437152:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[133345:1130/103630.437195:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
(node:133345) UnhandledPromiseRejectionWarning: TypeError: electron.app.setUserTasks is not a function
    at createSystemInfo (/home/zxp-endeavouros/.cache/paru/clone/splayer-bin/src/opt/SPlayer/resources/app.asar/out/main/index.js:58:16)
    at /home/zxp-endeavouros/.cache/paru/clone/splayer-bin/src/opt/SPlayer/resources/app.asar/out/main/index.js:2724:3
(Use `splayer --trace-warnings ...` to show where the warning was created)
(node:133345) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[133345:1130/103630.474544:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: 在路径 org.freedesktop.portal.Settings 的对象上没有“/org/freedesktop/portal/desktop”接口
(node:133345) electron: Failed to load URL: http://127.0.0.1:7899/ with error: ERR_CONNECTION_REFUSED
```
然后又下载了AppImage的包，运行报错：
```
$ ./SPlayer-2.0.0-beta.2.AppImage 
[134213:1130/103817.377324:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[134213:1130/103817.377365:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
(node:134213) UnhandledPromiseRejectionWarning: TypeError: electron.app.setUserTasks is not a function
    at createSystemInfo (/tmp/.mount_SPlayemAclST/resources/app.asar/out/main/index.js:58:16)
    at /tmp/.mount_SPlayemAclST/resources/app.asar/out/main/index.js:2724:3
(Use `splayer --trace-warnings ...` to show where the warning was created)
(node:134213) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[134213:1130/103817.696125:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: 在路径 org.freedesktop.portal.Settings 的对象上没有“/org/freedesktop/portal/desktop”接口
(node:134213) electron: Failed to load URL: http://127.0.0.1:7899/ with error: ERR_CONNECTION_REFUSED
```
似乎是客户端没有启动服务？

**Comment by imsyy** [comment]
抱歉，我对于 Linux 也不太懂 🤣，不过可以试下 v2.0.0-beta.3 版本，目前可在 Ubuntu 22.04 中正常运行

**Comment by wunewww** [comment]
@zxp19821005 你的XDG Desktop Portal的后端有问题，参考[Archwiki - XDG Desktop Portal#List of backends and interfaces](https://wiki.archlinux.org/title/XDG_Desktop_Portal#List_of_backends_and_interfaces)，换个后端

**Comment by zxp19821005** [comment]
@wunewww 感谢！
目前虽然运行报错：
![image](https://github.com/imsyy/SPlayer/assets/4915850/0dcb70d9-ea47-42cc-9886-7540ae1940ea)
但是点击“确认”之后可以正常使用。
另，按照ArchLinux的Electron相关打包准则，我使用系统自带的`electron27`运行如下命令：
```
env ELECTRON_IS_DEV=0 NODE_ENV=production path="./:$PATH" electron27 app.asar
```
```
env ELECTRON_IS_DEV=0 NODE_ENV=debug path="./:$PATH" electron27 app.asar
```
时报错：

**Comment by zxp19821005** [comment]
```
$ env ELECTRON_IS_DEV=0 NODE_ENV=debug path="./:$PATH" electron27 app.asar
11:39:35.025 › 主进程初始化
{ port: '11451', host: '127.0.0.1' }
server running @ http://127.0.0.1:11451
[173516:1222/113935.134618:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[173516:1222/113935.134805:ERROR:select_file_dialog_linux_portal.cc(280)] Failed to read portal version property
```

**Comment by wunewww** [comment]
> 目前虽然运行报错：
> image
> 但是点击“确认”之后可以正常使用。

你是用哪个提交构建的啊，[setUserTasks](https://www.electronjs.org/docs/latest/api/app#appsetusertaskstasks-windows)是windows下electron才会有的函数，我看了我本地构建出的`index.js` 应该不会有这个问题的。

```
$ env ELECTRON_IS_DEV=0 NODE_ENV=debug path="./:$PATH" electron27 app.asar
11:39:35.025 › 主进程初始化
{ port: '11451', host: '127.0.0.1' }
server running @ http://127.0.0.1:11451
[173516:1222/113935.134618:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[173516:1222/113935.134805:ERROR:select_file_dialog_linux_portal.cc(280)] Failed to read portal version property
```

从报错内容上看，应该还是之前说的portal的问题，你看看能不能想办法做一个fallback。一般来说应该是可以自动fallback，你试试这个[can't open file chooser in flatpak apps](https://www.reddit.com/r/swaywm/comments/15vgt8m/comment/jwwjek5/?context=3)

**Comment by imsyy** [comment]
@zxp19821005 `setUserTasks` 方法已于 https://github.com/imsyy/SPlayer/commit/883b6d13a579a77fe760e2aa24a2d99abd40fa4c 提交中去除，拉取下最新分支
